#ifndef _BS_IMAGE_DECODER_H_
#define _BS_IMAGE_DECODER_H_

#include <common.h>
#include <stdint.h>
#include <stddef.h>

// Decodes a texture blob (PNG, GameMaker custom QOI, or BZip2+QOI) into RGBA8 pixel data.
// "gm2022_5" should be set when it is a QOI image generated by GameMaker 2022.5+, because it includes the uncompressed length in the header.
// Returns a malloc'd buffer of size (*outW) * (*outH) * 4 bytes, or nullptr on failure.
// Caller is responsible for free()ing the returned buffer.
uint8_t* ImageDecoder_decodeToRgba(const uint8_t* blob, size_t blobSize, bool gm2022_5, int* outW, int* outH);

#endif /* _BS_IMAGE_DECODER_H_ */
